### ISSUE TITLE
Add codeclimate badges to README.md

### ISSUE THREAD

**Issue by cyri113** [RnDAO/pulseSurvey#95]
Badges will provide us with a quick overview of the status.

@daniel-ospina Tasks:
- [x] Follow instructions (https://docs.codeclimate.com/docs/overview#badges)
- [x] We want the **Markdown** version of the badges for both **Maintainability** and **Testing**.
- [x] Paste code as a comment in this issue

developer Tasks:
- [ ] Add both badges to the Readme.md file

**Comment by daniel-ospina** [comment]
[![Maintainability](https://api.codeclimate.com/v1/badges/bbe753726b9ecb129382/maintainability)](https://codeclimate.com/github/RnDAO/tc-botComm/maintainability)


[![Test Coverage](https://api.codeclimate.com/v1/badges/bbe753726b9ecb129382/test_coverage)](https://codeclimate.com/github/RnDAO/tc-botComm/test_coverage)

**Comment by cyri113** [comment]
No longer needed, botComm will be deprecated.
